language: java
sudo: false

env:
  - MVN="mvn --settings $TRAVIS_BUILD_DIR/.travis.settings.xml"

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script:
  - ${MVN} clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy:
  # decrypt ReTest secret key
  - openssl aes-256-cbc -K $encrypted_58a7d4f10478_key -iv $encrypted_58a7d4f10478_iv
      -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
  # import decrypted ReTest secret key
  - gpg --fast-import retest-gmbh-gpg.asc
  # package, sign and deploy artifacts
  - ${MVN} deploy -DskipTests -P sign

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/recheck-*.jar.*"
  skip_cleanup: true
  on:
    tags: true
