language: java
sudo: false

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.m2/"

env:
  global:
    secure: VLMsg7+JEx+Uunh7BVBtBG44D1puKKLUkJH0KElNzqb0WiAzmQne6JfBiM4R/kbHpp5PTq71FKrEBotwQeVvYh3H04D+E7dYvaScfB6O722CeuRHiYlOPLFuuD8aGIT7/ui13JBTXbdUdnl9zKZxIyYOCNx11jyPf5qUYVsZJcjZ95yuApN5fW6itHerTjPF508+roXP8nkcmTKbnYTM7CoNvA1SIy4o6YibN4Nd4D5JuZlwVtL0eyabb4yYQ4yy78n+a58FEXJlnWMQifa3I2WJsP3DsYoh9VV4nxz+kOqHQmDbhk9qFHhcflQ4s9gis8G72bquCBUN0IINican4XhOfVEnTLr4B8biuHn3mJAnhVJOJItjvtr4tLjcs/6pIRKpto/gAotM5/o+Ua/kCMBQuw267uCPmxyWrKea3/kOBFzz9X+DHkca8fjAGb4LFNEXoQe6La5IpMfMe4Tsn/8w5tEVHuVbMBzTRyYw3nQLwctCdhmK5p91HfUb7eqArQmNb7ciLyYlsVcFaPa0/tRQewX3DmLuUW9HVC7yCzCRXlTjf/VmRfnCnQhaV1Eu8xcGri+m8JMfQbhTQrOfqLBVCPLuWWM6wRv0qIPwfmWnaSbuom9I3CNeT3yCedU1jxmk9MAiRXpuKT7sYoP6xEXecN2Cj0Urd+HZdQoSRmw=


before_install:
- openssl aes-256-cbc -K $encrypted_58a7d4f10478_key -iv $encrypted_58a7d4f10478_iv
  -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
- gpg --fast-import retest-gmbh-gpg.asc

install: true

before_deploy: mvn package -DskipTests --settings mvnsettings.xml

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/recheck-*.jar"
  skip_cleanup: true
  on:
    tags: true
    branch: master

